version: '3'

services:
  backend-v1:
    build: ./backend
    ports:
      - "58081:80"
    environment:
      DEMO_FOREGROUND_COLOUR: "blue"

  frontend:
    build: ./frontend
    ports:
      - "58080:80"
    environment:
      BACKEND_SERVICE_HOST: "backend-v1"
      BACKEND_SERVICE_PORT: "80"
    depends_on:
      - backend-v1

# Not used by frontend, just getting it built & running
  backend-v2:
    build: ./backend
    ports:
      - "58082:80"
    environment:
      DEMO_FOREGROUND_COLOUR: "green"
