version: '3'

services:
  frontend-v2:
    image: demoapp_frontend:v2
    ports:
      - "58008:80"
    environment:
      BACKEND_SERVICE_HOST: "backend-v2"
      BACKEND_SERVICE_PORT: "80"
    depends_on:
      - backend-v2


  backend-v2:
    image: demoapp_backend:v2
    ports:
      - "58082:80"
    environment:
      DEMO_FOREGROUND_COLOUR: "green"
