version: '3'

services:
  backend-v1:
    build: ./backend
    ports:
      - "58081:80"
    environment:
      DEMO_FOREGROUND_COLOUR: "blue"
    volumes:
      - backend-volume:/app

  frontend:
    build: ./frontend
    ports:
      - "58080:80"
    environment:
      BACKEND_SERVICE_HOST: "backend-v1"
      BACKEND_SERVICE_PORT: "80"
    volumes:
      - frontend-volume:/app
    depends_on:
      - backend-v1

# Not used by frontend, just getting it built & running
  backend-v2:
    build: ./backend
    ports:
      - "58082:80"
    environment:
      DEMO_FOREGROUND_COLOUR: "green"
# The volumes allow live reloading (touch uwsgi.ini)
    volumes:
      - backend-volume:/app

volumes:
  backend-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend'

  frontend-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './frontend'
