version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "58081:80"
    environment:
      DEMO_FOREGROUND_COLOUR: "magenta"
    volumes:
      - backend-volume:/app


  frontend:
    build: ./frontend
    ports:
      - "58080:80"
    volumes:
      - frontend-volume:/app
    depends_on:
      - backend

volumes:
  backend-volume:
    name: backend-volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend'

  frontend-volume:
    name: frontend-volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './frontend'
