---
# This is going to load balance across backend-v1 and backend-v2
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    version: v2
spec:
  ports:
    - name: http-80
      port: 80
  selector:
    app: backend
    version: v2
