# version pinnned
FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
RUN apk --update add bash nano
ENV STATIC_URL /static
ENV STATIC_PATH /var/www/app/static
COPY ./main.py /app/
COPY ./app /app/app
COPY ./uwsgi.ini /app/
COPY ./requirements.txt /var/www/requirements.txt
RUN pip install -r /var/www/requirements.txt
