apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-v2
  labels:
    app: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
        - name: backend
          image: demoapp_backend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DEMO_FOREGROUND_COLOUR
              value: green
#          volumeMounts:
#            - mountPath: /app
#              name: backend-volume
#      volumes:
#        - name: backend-volume
#          persistentVolumeClaim:
#            claimName: backend-volume-claim
#