---
# This is going to load balance across backend-v1 and backend-v2
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: backend
