apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
  - name: "58081"
    port: 58081
    targetPort: 80
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
