---
# relying on images built by docker-compose earlier
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-v2
  labels:
    app: backend
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: demoapp_backend-v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DEMO_FOREGROUND_COLOUR
              value: khaki
