apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "58080"
    port: 58080
    targetPort: 80
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
