---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-v1
  labels:
    app: frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: demoapp_frontend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
